services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: my_sql_server
    hostname: PI
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=12345678Aa!
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      echo 'Waiting for SQL Server to start...' &&
      until /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 12345678Aa! -N o -Q 'SELECT 1' > /dev/null 2>&1;
      do
        echo 'SQL Server is not ready yet...';
        sleep 2;
      done &&
      echo 'SQL Server is ready!' &&
      echo 'Creating custom database...' &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 12345678Aa! -N o -Q 'IF DB_ID(NCHAR(116)+NCHAR(101)+NCHAR(115)+NCHAR(116)) IS NULL CREATE DATABASE [test];' &&
      echo 'Database initialization complete.' &&
      wait
      "
